'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Box,Wind,CircleDot,Monitor,ArrowUpRight,Power,Play,Pause,Home as HomeIcon,Wifi,WifiOff,Volume2,Check,MousePointer2,Leaf,ChevronRight,Activity} from 'lucide-react';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Progress} from '@/components/ui/progress';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {applyCommand,initialState,tick,modeLabels,type Command,type DeviceId,type SimState} from '@/lib/simulation';
import RoomScene from './scene';
const devices=[{id:'purifier' as const,name:'空氣清淨機',place:'窗邊',icon:Wind,type:'Matter · 空氣清淨機'},{id:'vacuum' as const,name:'掃地機器人',place:'入口',icon:CircleDot,type:'Matter · 掃地機器人'},{id:'hub' as const,name:'Google Nest Hub',place:'工作桌',icon:Monitor,type:'Google Home · 家庭中樞'}];
export default function Home(){
 const [selected,setSelected]=useState<DeviceId|null>(null);const [state,setState]=useState<SimState>(initialState);const stateRef=useRef(state);stateRef.current=state;const [pending,setPending]=useState(false);const pendingRef=useRef(false);const [message,setMessage]=useState('選取模型中的設備，即可開始操作。');const [events,setEvents]=useState<string[]>([]);const [air,setAir]=useState(false);const [fanDraft,setFanDraft]=useState(40);const [volumeDraft,setVolumeDraft]=useState(35);const alive=useRef(true);
 useEffect(()=>{alive.current=true;let last=performance.now();const timer=setInterval(()=>{const now=performance.now();setState(s=>tick(s,(now-last)/1000));last=now},300);return ()=>{alive.current=false;clearInterval(timer)}},[]);
 const command=useCallback(async(c:Command)=>{
  if(pendingRef.current)throw Error('請等待上一個指令完成。');
  applyCommand(stateRef.current,c);pendingRef.current=true;setPending(true);setMessage('正在送出模擬指令…');
  try{await new Promise(resolve=>setTimeout(resolve,450));if(!alive.current)return;const next=applyCommand(stateRef.current,c);stateRef.current=next;setState(next);const name=devices.find(d=>d.id===c.device)!.name;const action=c.action==='power'?(c.value?'已開啟':'已關閉'):c.action==='fan'?`風速已調為 ${c.value}%`:c.action==='volume'?`音量已調為 ${c.value}%`:c.action==='start'?'已開始清掃':c.action==='pause'?'已暫停':'已收到回充指令';const msg=`${name}${action}`;setMessage(msg+' · 模擬已回應');setEvents(e=>[msg,...e].slice(0,3));return {mode:'simulation',device:c.device,state:next[c.device]};
  }finally{pendingRef.current=false;if(alive.current)setPending(false)}
 },[]);
 const send=(c:Command)=>{void command(c).catch(e=>setMessage(e.message))};
 const select=useCallback((id:DeviceId)=>{setSelected(id);setFanDraft(stateRef.current.purifier.fan);setVolumeDraft(stateRef.current.hub.volume)},[]);
 useEffect(()=>{
  type Context={registerTool:(tool:{name:string;description:string;inputSchema:object;annotations:object;execute:(input:any)=>unknown},options:{signal:AbortSignal})=>void|Promise<void>};
  const context=(document as Document&{modelContext?:Context}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();
  const defs=[{name:'read_simulated_home',description:'Read the simulated device states. No real devices are connected.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({mode:'simulation',state:stateRef.current})},{name:'control_simulated_device',description:'Control a simulated purifier (power/fan), vacuum (start/pause/dock), or hub (volume); updates the visible 3D home. Does not control real hardware.',inputSchema:{type:'object',properties:{device:{enum:['purifier','vacuum','hub']},action:{enum:['power','fan','start','pause','dock','volume']},value:{type:['number','boolean']}},required:['device','action'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:any)=>{if(!input||typeof input!=='object'||!['purifier','vacuum','hub'].includes(input.device)||Object.keys(input).some(k=>!['device','action','value'].includes(k)))throw Error('Invalid command');const result=await command(input);select(input.device);await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));return result}}];
  defs.forEach(d=>{try{void Promise.resolve(context.registerTool(d,{signal:lifecycle.signal})).catch(()=>{})}catch{}});return ()=>lifecycle.abort();
 },[command,select]);
 const current=devices.find(d=>d.id===selected);const offline=selected===state.offline;const disabled=pending||offline;const pm=Math.round(state.purifier.pm25);const connected=3-(state.offline?1:0);
 function status(id:DeviceId){return state.offline===id?'離線':id==='purifier'?(state.purifier.on?`${state.purifier.fan}% 風速`:'已關閉'):id==='vacuum'?modeLabels[state.vacuum.mode]:'中樞待命'}
 return <main className="home-app"><header className="topbar"><div className="brand"><Box/> HOME<span>3D</span></div><div className="breadcrumb">我的空間 <span>/</span> 辦公室</div><span className="sim-badge">模擬模式</span></header>
 <div className="workspace"><aside className="inventory"><p className="eyebrow">MY HOME</p><h1>空間，就是介面。</h1><p className="intro">點選家中的設備，<br/>就從它所在的位置操作。</p><div className="section-label">辦公室 <span>3 個設備</span></div>
 {devices.map(d=><button className={'device-row '+(selected===d.id?'active':'')} key={d.id} onClick={()=>select(d.id)} aria-pressed={selected===d.id}><d.icon/><span><strong>{d.name}</strong><small><i className={state.offline===d.id?'status-dot off':'status-dot'}/>{status(d.id)}</small></span><ArrowUpRight size={14}/></button>)}
 <div className="connection-card"><span className="connection-icon"><Wifi size={17}/></span><div><strong>{connected} / 3 模擬設備在線</strong><small>Google Home 空間</small></div></div>
 <div className="event-list"><p className="eyebrow">最近操作</p>{events.length?events.map((e,i)=><p key={i}><Check size={13}/>{e}</p>):<p>操作後，設備回應會顯示在這裡。</p>}</div>
 <p className="simulation-note">此展示未連接真實設備。<br/>空間比例依照片估算。<br/>重新整理會重設所有模擬狀態。</p></aside>
 <section className={'stage '+(selected?'has-selection':'')}><div className="stage-heading"><p className="eyebrow">SPATIAL CONTROL / 01</p><h2>辦公室</h2><p>直接點選設備，讓空間回應你。</p></div><div className="stage-metrics"><span><Leaf size={15}/> PM2.5 <strong>{pm}</strong><small>μg/m³</small></span><small>模擬讀值</small></div>
 <RoomScene state={state} selected={selected} onSelect={select} air={air}/>
 <div className="view-toggle"><Switch id="air-layer" checked={air} onCheckedChange={setAir}/><label htmlFor="air-layer">空氣狀態示意</label></div>
 <div className="stage-help"><MousePointer2 size={15}/><span>點選設備操作 <b>·</b> 拖曳旋轉 <b>·</b> 滾輪縮放</span></div><div className="stage-corner">照片重建 <span>5.4 × 7.2 m（估算）</span></div></section></div>
 <footer className="activity-bar" role="status" aria-live="polite"><span className={pending?'activity-dot pending':'activity-dot'}/>{message}<span className="footer-caption">指令與動線皆為模擬</span></footer>
 <Sheet modal={false} disablePointerDismissal open={!!selected} onOpenChange={open=>{if(!open)setSelected(null)}}><SheetContent className="device-sheet" initialFocus={true}>
 {current&&<><SheetHeader><p className="eyebrow">{current.place} / DEVICE CONTROL</p><div className="panel-icon"><current.icon size={30}/></div><SheetTitle className="panel-title">{current.name}</SheetTitle><SheetDescription className="panel-description">{current.type} · 模擬設備</SheetDescription></SheetHeader><div className="panel-body"><div className={'device-status '+(offline?'is-offline':'')}>{offline?<WifiOff size={15}/>:<span className="status-dot"/>}{status(current.id)}<span>{pending?'等待回應…':'模擬狀態'}</span></div>
 {offline&&<p className="offline-hint">設備目前離線，操作已停用。恢復連線後即可繼續模擬。</p>}
 {selected==='purifier'&&<><div className="air-reading"><p>PM2.5 <span>μg/m³</span></p><strong>{pm}<span className="reading-unit">模擬讀值</span></strong><small>{state.purifier.on?'清淨機運作中，讀值將逐漸下降':'清淨機已關閉'}</small></div><div className="control-row"><label htmlFor="purifier-power"><Power size={17}/>電源</label><Switch id="purifier-power" checked={state.purifier.on} disabled={disabled} onCheckedChange={v=>send({device:'purifier',action:'power',value:v})}/></div><div className="range-label"><label id="fan-label">風速</label><strong>{fanDraft}%</strong></div><Slider aria-labelledby="fan-label" min={1} max={100} step={1} value={[fanDraft]} disabled={disabled} onValueChange={v=>setFanDraft(Array.isArray(v)?v[0]:v)} onValueCommitted={v=>send({device:'purifier',action:'fan',value:Array.isArray(v)?v[0]:v})}/><div className="range-ends"><span>安靜</span><span>強效</span></div><div className="mode-buttons">{[{name:'安靜',value:20},{name:'日常',value:50},{name:'強效',value:100}].map(m=><button key={m.name} disabled={disabled} className={state.purifier.fan===m.value?'chosen':''} onClick={()=>{setFanDraft(m.value);send({device:'purifier',action:'fan',value:m.value})}}>{m.name}<span>{m.value}%</span></button>)}</div><p className="panel-note">風速變化會同步呈現在清淨機上方的氣流。空氣色層是示意，不代表真實感測範圍。</p></>}
 {selected==='vacuum'&&<><div className="vacuum-reading"><CircleDot size={53} className={state.vacuum.mode==='cleaning'?'spin-slow':''}/><strong>{Math.round(state.vacuum.progress)}<span>%</span></strong><p>展示路線進度</p></div><Progress value={state.vacuum.progress} aria-label="清掃模擬進度"/><div className="range-ends"><span>入口 → 窗側走道</span><span>電量 {Math.round(state.vacuum.battery)}%</span></div><button className="primary-action" disabled={disabled||state.vacuum.mode==='returning'} onClick={()=>send({device:'vacuum',action:state.vacuum.mode==='cleaning'?'pause':'start'})}>{state.vacuum.mode==='cleaning'?<Pause size={18}/>:<Play size={18}/>} {state.vacuum.mode==='cleaning'?'暫停清掃':state.vacuum.mode==='paused'?'繼續清掃':'開始清掃'}</button><button className="secondary-action" disabled={disabled||state.vacuum.mode==='docked'||state.vacuum.mode==='returning'} onClick={()=>send({device:'vacuum',action:'dock'})}><HomeIcon size={18}/>返回充電座</button><p className="panel-note">在空間中查看機器人的位置與行走軌跡。展示採用約 70 秒的預設路線；真實定位與地圖需依設備能力整合。</p></>}
 {selected==='hub'&&<><div className="hub-info"><span className="google-dots"><i/><i/><i/><i/></span><h3>Google Home</h3><p>家庭中樞示意</p><div><strong>{connected}</strong><span>個模擬設備在線</span></div></div><div className="range-label"><label id="volume-label"><Volume2 size={17}/> 音量</label><strong>{volumeDraft}%</strong></div><Slider aria-labelledby="volume-label" min={0} max={100} value={[volumeDraft]} disabled={disabled} onValueChange={v=>setVolumeDraft(Array.isArray(v)?v[0]:v)} onValueCommitted={v=>send({device:'hub',action:'volume',value:Array.isArray(v)?v[0]:v})}/><div className="range-ends"><span>靜音</span><span>最大</span></div><p className="panel-note">這是 Google Nest Hub 的空間化操作概念，沒有 Google 帳戶連線、語音收音或音訊播放。音量僅更新示意值。</p><div className="hub-links">{devices.filter(d=>d.id!=='hub').map(d=><button key={d.id} onClick={()=>select(d.id)}><d.icon size={18}/>{d.name}<ChevronRight size={16}/></button>)}</div></>}
 <div className="simulation-tools"><button disabled={pending} onClick={()=>{setState(s=>({...s,offline:offline?null:selected}));setMessage(offline?'模擬設備已恢復連線':'已模擬設備離線，控制暫停。')}}>{offline?<Wifi size={14}/>:<WifiOff size={14}/>} {offline?'恢復模擬連線':'體驗設備離線'}</button></div></div></>}
 </SheetContent></Sheet>
 </main>
}
