import * as T from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
import {pointOnRoute,routePoints,curtainSpan,type DeviceId,type SimState} from '@/lib/simulation';
export type SceneController={dispose:()=>void;reset:()=>void;top:()=>void;zoom:(factor:number)=>void};
export async function createScene(host:HTMLDivElement,get:()=>{state:SimState;selected:DeviceId|null;air:boolean},select:(id:DeviceId)=>void,labels:Record<string,HTMLButtonElement|null>,ready:()=>void):Promise<SceneController>{
 const renderer=new T.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.18;host.appendChild(renderer.domElement);
 const scene=new T.Scene();const camera=new T.PerspectiveCamera(39,1,.1,120);camera.up.set(0,0,1);camera.position.set(-9,-8,10.5);
 const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,3.6,.5);controls.enableDamping=true;controls.minDistance=6;controls.maxDistance=25;controls.maxPolarAngle=Math.PI*.47;controls.minPolarAngle=.02;controls.enablePan=false;controls.update();
 scene.add(new T.AmbientLight(0xcbdcf4,1.55));const sun=new T.DirectionalLight(0xffefda,3);sun.position.set(-3,-1,10);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-9;sun.shadow.camera.right=9;sun.shadow.camera.top=9;sun.shadow.camera.bottom=-9;sun.shadow.normalBias=.035;sun.target.position.set(0,3,0);scene.add(sun,sun.target);const fill=new T.DirectionalLight(0x9fcbff,1.8);fill.position.set(4,5,6);scene.add(fill);
 let model:T.Group;try{const gltf=await new GLTFLoader().loadAsync('/models/office.glb');model=gltf.scene;model.rotation.x=Math.PI/2;model.traverse(o=>{if(o instanceof T.Mesh){o.castShadow=true;o.receiveShadow=true;const mats=Array.isArray(o.material)?o.material:[o.material];mats.forEach(m=>{if(m instanceof T.MeshStandardMaterial){m.roughness=.75;}});if(/air[ _]conditioner|curtain[ _]fold|electrical[ _]panel|Television/i.test(o.name))o.visible=false;}});scene.add(model);}catch(e){renderer.dispose();renderer.domElement.remove();controls.dispose();throw e;}
 const back=new T.Mesh(new T.BoxGeometry(5.55,.1,1.35),new T.MeshStandardMaterial({color:0xc8c9c1}));back.position.set(0,7.28,.63);back.receiveShadow=true;scene.add(back);
 const shadow=new T.Mesh(new T.PlaneGeometry(50,50),new T.ShadowMaterial({opacity:.20}));shadow.position.set(0,3.6,-.22);shadow.receiveShadow=true;scene.add(shadow);
 const grid=new T.GridHelper(30,60,0x42545e,0x35454f);grid.rotation.x=Math.PI/2;grid.position.set(0,3.6,-.24);(grid.material as T.Material).transparent=true;(grid.material as T.Material).opacity=.24;scene.add(grid);
 const devices={} as Record<DeviceId,T.Group>;const pickables:T.Object3D[]=[];
 const m=(color:number)=>new T.MeshStandardMaterial({color,roughness:.48,metalness:.08});const ivory=m(0xecefe9),dark=m(0x202c32),lime=m(0xb9ee70);
 function box(g:T.Group,dim:number[],p:number[],mat:T.Material){const o=new T.Mesh(new RoundedBoxGeometry(dim[0],dim[1],dim[2],3,.03),mat);o.position.set(p[0],p[1],p[2]);o.castShadow=true;g.add(o);return o}
 function cyl(g:T.Group,r:number,h:number,p:number[],mat:T.Material){const o=new T.Mesh(new T.CylinderGeometry(r,r,h,48),mat);o.rotation.x=Math.PI/2;o.position.set(p[0],p[1],p[2]);o.castShadow=true;g.add(o);return o}
 for(const id of ['hub','purifier','vacuum','curtain','ac'] as DeviceId[]){const g=new T.Group();devices[id]=g;scene.add(g);g.userData.device=id;}
 const hub=devices.hub;hub.position.set(1.60,6.23,.82);box(hub,[.38,.18,.10],[0,.03,.02],ivory);box(hub,[.42,.045,.27],[0,0,.18],ivory);const hubScreen=box(hub,[.37,.008,.215],[0,-.027,.18],new T.MeshBasicMaterial({color:0x23475a}));for(let i=0;i<4;i++)box(hub,[.038,.01,.025],[-.10+i*.067,-.036,.20],m([0x80b3f7,0xf87973,0xf3d075,0x83d3a5][i]));box(hub,[.22,.01,.014],[0,-.036,.12],ivory);
 const purifier=devices.purifier;purifier.position.set(2.10,4.8,.03);box(purifier,[.44,.40,.75],[0,0,.385],ivory);box(purifier,[.37,.32,.035],[0,0,.78],dark);for(let i=0;i<12;i++)box(purifier,[.31,.011,.013],[0,-.205,.14+i*.038],m(0xb4c1c6));box(purifier,[.11,.014,.025],[0,-.209,.69],lime);
 const vacuum=devices.vacuum;vacuum.position.set(1.68,.75,.075);cyl(vacuum,.205,.11,[0,0,0],dark);cyl(vacuum,.198,.04,[0,0,.06],ivory);cyl(vacuum,.055,.04,[0,.02,.1],dark);box(vacuum,[.045,.055,.01],[0,-.09,.089],lime);
 const curtain=devices.curtain;curtain.position.set(2.55,2.0,0);const curtainFolds:Array<{mesh:T.Mesh;start:number;span:number;index:number}>=[];const fabric=m(0x627b9c);
 for(const [center,span] of [[2.0,2.6],[5.25,2.7]]){box(curtain,[.075,span+.1,.06],[0,center-2,2.40],dark);for(let i=0;i<24;i++){const fold=box(curtain,[.085,.13,2.27],[0,0,1.20],fabric);curtainFolds.push({mesh:fold,start:center-span/2-2,span,index:i});}}
 const ac=devices.ac;ac.position.set(-2.54,1.50,2.63);box(ac,[.32,1.06,.35],[0,0,0],ivory);box(ac,[.012,.89,.08],[.168,0,-.085],dark);const acFlap=box(ac,[.12,.89,.035],[.18,0,-.12],ivory);const acLed=box(ac,[.015,.06,.025],[.17,-.31,.035],lime);
 const acFlow=new T.Group();acFlow.position.copy(ac.position);scene.add(acFlow);for(let i=0;i<5;i++){const r=new T.Mesh(new T.RingGeometry(.12,.135,40),new T.MeshBasicMaterial({color:0x8dccff,transparent:true,opacity:.4,side:T.DoubleSide,depthWrite:false}));r.rotation.y=Math.PI/2;acFlow.add(r);}
 const dock=new T.Group();dock.position.set(1.68,.38,0);box(dock,[.48,.20,.32],[0,0,.16],dark);scene.add(dock);
 const halos={} as Record<DeviceId,T.Mesh>;for(const id of Object.keys(devices) as DeviceId[]){const d=devices[id];d.traverse(o=>{o.userData.device=id;if(o instanceof T.Mesh)pickables.push(o)});const hit=new T.Mesh(new T.SphereGeometry(id==='hub'?.35:.39),new T.MeshBasicMaterial({visible:false}));hit.position.z=id==='purifier'?.4:id==='hub'?.16:0;hit.userData.device=id;d.add(hit);pickables.push(hit);const ring=new T.Mesh(new T.RingGeometry(.31,.34,64),new T.MeshBasicMaterial({color:0xb9f674,transparent:true,opacity:.8,side:T.DoubleSide}));ring.position.copy(d.position);ring.position.z=id==='hub'?.815:id==='ac'?2.63:.045;if(id==='ac'){ring.rotation.y=Math.PI/2;ring.position.x+=.20;}scene.add(ring);halos[id]=ring;}
 const flow=new T.Group();flow.position.copy(purifier.position);scene.add(flow);for(let i=0;i<4;i++){const r=new T.Mesh(new T.RingGeometry(.32,.34,64),new T.MeshBasicMaterial({color:0x82e6c7,transparent:true,opacity:.25,side:T.DoubleSide,depthWrite:false}));r.position.z=.83+i*.19;flow.add(r);}
 const heat=new T.Mesh(new T.CircleGeometry(1.6,80),new T.MeshBasicMaterial({color:0x91e6b1,transparent:true,opacity:.14,depthWrite:false}));heat.position.set(1.0,4.8,.035);scene.add(heat);
 const line=new T.Line(new T.BufferGeometry().setFromPoints(routePoints.map(([x,y])=>new T.Vector3(x,y,.04))),new T.LineDashedMaterial({color:0xc5f68b,dashSize:.10,gapSize:.075,transparent:true,opacity:.75}));line.computeLineDistances();scene.add(line);
 const ray=new T.Raycaster();const pointer=new T.Vector2();let start=[0,0];function pick(e:PointerEvent){const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);return ray.intersectObjects(pickables,false)[0]?.object.userData.device as DeviceId|undefined;}
 const down=(e:PointerEvent)=>{start=[e.clientX,e.clientY]};const up=(e:PointerEvent)=>{if(Math.hypot(e.clientX-start[0],e.clientY-start[1])<6){const id=pick(e);if(id)select(id)}};const move=(e:PointerEvent)=>{renderer.domElement.style.cursor=pick(e)?'pointer':'grab'};renderer.domElement.addEventListener('pointerdown',down);renderer.domElement.addEventListener('pointerup',up);renderer.domElement.addEventListener('pointermove',move);
 let width=1,height=1;const resize=()=>{width=host.clientWidth;height=host.clientHeight;renderer.setSize(width,height);camera.aspect=width/height;camera.updateProjectionMatrix()};const observer=new ResizeObserver(resize);observer.observe(host);resize();let raf=0;const projected=new T.Vector3();const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 function animate(time:number){const {state,selected,air}=get();controls.update();const [x,y]=pointOnRoute(state.vacuum.route);vacuum.position.set(x,y,.075);line.visible=state.vacuum.mode!=='docked';flow.visible=state.purifier.on&&state.offline!=='purifier';heat.visible=air;
 for(const fold of curtainFolds){const width=curtainSpan(state.curtain.opening,fold.span);fold.mesh.position.y=fold.start+(fold.index+.5)*width/24;fold.mesh.position.x=Math.sin(fold.index*Math.PI/2)*.025;fold.mesh.scale.y=(width/24+.008)/.13;}
 fill.intensity=.45+state.curtain.opening/100*1.35;
 acFlow.visible=state.ac.on&&state.offline!=='ac';acFlap.rotation.y=state.ac.on?-.55:0;acLed.visible=state.ac.on;
 for(let i=0;i<acFlow.children.length;i++){const r=acFlow.children[i] as T.Mesh;const phase=reduced?.5:(time/(3500-state.ac.fan*20)+i/5)%1;r.position.set(.24+phase*1.35,0,-.15-phase*.4);r.scale.setScalar(1+phase*1.8);const material=r.material as T.MeshBasicMaterial;material.color.set(state.ac.mode==='heat'?0xffba87:state.ac.mode==='fan'?0xc4e7d4:0x8dccff);material.opacity=(1-phase)*.40;}
 for(let i=0;i<flow.children.length;i++){const ring=flow.children[i] as T.Mesh;const phase=reduced?.4:(time/(3500-state.purifier.fan*23)+i*.25)%1;ring.scale.setScalar(1+phase*.9);ring.position.z=.80+phase*.75;(ring.material as T.MeshBasicMaterial).opacity=(1-phase)*.35;}
 heat.scale.setScalar(.8+state.purifier.fan/150);(heat.material as T.MeshBasicMaterial).color.set(state.purifier.pm25>15?0xeac179:0x8de5af);
 for(const id of Object.keys(devices) as DeviceId[]){const d=devices[id];const halo=halos[id];halo.position.x=d.position.x;halo.position.y=d.position.y;(halo.material as T.MeshBasicMaterial).color.set(state.offline===id?0x9babb3:selected===id?0xc9ff8b:0x7ea18a);halo.scale.setScalar(selected===id?1.3:1);
 projected.copy(d.position);projected.z+=id==='purifier'?.95:id==='hub'?.48:id==='curtain'?2.6:id==='ac'?.45:.4;projected.project(camera);const el=labels[id];if(el){const left=(projected.x*.5+.5)*width,top=(-projected.y*.5+.5)*height;el.style.left=`${Math.max(82,Math.min(width-82,left))}px`;el.style.top=`${Math.max(155,Math.min(height-100,top))}px`;el.style.opacity=projected.z>1?'0':'1';}}
 renderer.render(scene,camera);raf=requestAnimationFrame(animate);
 }
 raf=requestAnimationFrame(animate);ready();
 return {reset(){camera.position.set(-9,-8,10.5);controls.target.set(0,3.6,.5);controls.update()},top(){camera.position.set(.02,3.3,15);controls.target.set(0,3.6,0);controls.update()},zoom(factor){camera.position.sub(controls.target).multiplyScalar(factor).add(controls.target);controls.update()},dispose(){cancelAnimationFrame(raf);observer.disconnect();controls.dispose();renderer.domElement.removeEventListener('pointerdown',down);renderer.domElement.removeEventListener('pointerup',up);renderer.domElement.removeEventListener('pointermove',move);scene.traverse(o=>{if(o instanceof T.Mesh||o instanceof T.Line){o.geometry.dispose();const materials=Array.isArray(o.material)?o.material:[o.material];materials.forEach(mat=>mat.dispose())}});renderer.dispose();renderer.domElement.remove()}};
}
